---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chromadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chromadb
  template:
    metadata:
      labels:
        app: chromadb
    spec:
      containers:
        - name: chromadb
          image: chromadb/chroma
          env:
            - name: CHROME_USER_DATA_DIR
              value: /chromadb/data
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: chromadb-data
              mountPath: /chromadb/data
      volumes:
        - name: chromadb-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: chromadb
spec:
  selector:
    app: chromadb
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000