name: Test

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:

jobs:
  test-start-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - name: test
        uses: ./.github/start-server
      - uses: actions/upload-artifact@v4
        if: ${{ !success() }}
        with:
          name: server-logs
          path: container_logs.txt

  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: |
          pipx install poetry
          make poetry.lock
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'poetry'
      - run: |
          set +o pipefail
          yes TESTVALUE | make .env
          set -o pipefail
      - run: make test
